name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g bats
      - run: bats -v
      -
        name: TF apply
        uses: hashicorp/setup-terraform@v1
        run: terraform apply
      - 
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ADMIN_USER_ID }}
          aws-secret-access-key: ${{ secrets.ADMIN_USER_KEY }}
          aws-region: us-east-1

      - 
        name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      # - 
      #   name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./back/
      #     push: true
      #     tags: user/app:latest
      # - 
      #   name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}
